"""Initial migration

Revision ID: 0d7f93e451ac
Revises: 148dfbea7378
Create Date: 2023-07-24 17:14:04.497741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d7f93e451ac'
down_revision = '148dfbea7378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('balance', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
