"""Initial migration

Revision ID: 148dfbea7378
Revises: b06bbb1135a3
Create Date: 2023-07-24 16:29:54.706485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '148dfbea7378'
down_revision = 'b06bbb1135a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expenses', sa.Column('money', sa.Float(), nullable=True))
    op.drop_column('Expenses', 'balance')
    op.add_column('process', sa.Column('connection', sa.String(length=255), nullable=True))
    op.add_column('process', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.drop_column('process', 'connections')
    op.drop_column('process', 'toquvchi_id')
    op.drop_column('process', 'tool_id')
    op.drop_column('process', 'home_id')
    op.add_column('tools', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'balance')
    op.add_column('process', sa.Column('home_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('process', sa.Column('tool_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('process', sa.Column('toquvchi_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('process', sa.Column('connections', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('process', 'connection_id')
    op.drop_column('process', 'connection')
    op.add_column('Expenses', sa.Column('balance', mysql.FLOAT(), nullable=True))
    op.drop_column('Expenses', 'money')
    # ### end Alembic commands ###
