"""Initial migration

Revision ID: 430eda9fa2bb
Revises: ce3da71a5993
Create Date: 2023-07-28 14:41:32.172260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '430eda9fa2bb'
down_revision = 'ce3da71a5993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'connection')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('connection', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
