"""Initial migration

Revision ID: 79e262156ed6
Revises: b87474aaefea
Create Date: 2023-07-28 14:34:42.794890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e262156ed6'
down_revision = 'b87474aaefea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
