"""Initial migration

Revision ID: 80712464d580
Revises: 855d9abab088
Create Date: 2023-07-23 10:14:50.883011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80712464d580'
down_revision = '855d9abab088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_history', 'user_id')
    op.drop_column('process', 'user_id')
    # ### end Alembic commands ###
