"""Initial migration

Revision ID: 855d9abab088
Revises: f004f37a8b80
Create Date: 2023-07-22 15:30:26.320643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d9abab088'
down_revision = 'f004f37a8b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
