"""Initial migration

Revision ID: b06bbb1135a3
Revises: 68a785a56e61
Create Date: 2023-07-24 14:22:38.874536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06bbb1135a3'
down_revision = '68a785a56e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('toquvchi_id', sa.Integer(), nullable=True))
    op.add_column('process', sa.Column('home_id', sa.Integer(), nullable=True))
    op.add_column('process', sa.Column('tool_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'tool_id')
    op.drop_column('process', 'home_id')
    op.drop_column('process', 'toquvchi_id')
    # ### end Alembic commands ###
