"""Initial migration

Revision ID: b87474aaefea
Revises: 8503d46cde93
Create Date: 2023-07-28 11:05:59.284194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87474aaefea'
down_revision = '8503d46cde93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homes', 'name')
    # ### end Alembic commands ###
