"""Initial migration

Revision ID: bf6958897437
Revises: b2d2f72e015e
Create Date: 2023-07-28 15:16:38.314577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6958897437'
down_revision = 'b2d2f72e015e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
