"""Initial migration

Revision ID: ce3da71a5993
Revises: 79e262156ed6
Create Date: 2023-07-28 14:40:26.957384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3da71a5993'
down_revision = '79e262156ed6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
