"""Initial migration

Revision ID: f004f37a8b80
Revises: d8a3cfe7169e
Create Date: 2023-07-22 15:26:52.361994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f004f37a8b80'
down_revision = 'd8a3cfe7169e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('homes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('toquvchilar', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('process_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('home_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('tool_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('toquvchi_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('draw_id', sa.Integer(), nullable=True))
    op.add_column('work_history', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('work_history', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_history', 'date')
    op.drop_column('work_history', 'status')
    op.drop_column('work_history', 'draw_id')
    op.drop_column('work_history', 'toquvchi_id')
    op.drop_column('work_history', 'tool_id')
    op.drop_column('work_history', 'home_id')
    op.drop_column('work_history', 'process_id')
    op.drop_column('toquvchilar', 'user_id')
    op.drop_column('homes', 'user_id')
    op.drop_column('homes', 'balance')
    # ### end Alembic commands ###
