from database import Base
from models.draws import Draws
from models.kpi import Kpi
from models.material_type import Material_type
from models.proces import Process
from models.products import Products
from models.store import Stores
from models.suppliers import Suppliers
from models.supplies import Supplies
from models.tools import Tools
from models.warehouse_products import Warehouse_products
from models.work import Work
from models.toquvchilar import Toquvchilar
from models.homes import Homes
from models.work_history import Work_history
from models.kpi_histories import Kpi_history
from models.expenses import Expenses